# docker compose file to test in development
# for production example please see README.md or ./examples

version: "3"
services:
  filestation:
    build: .
    # image: korki43/filestation:latest
    container_name: filestation
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - $PWD/files:/app/files/root
